version: '3.1'

services:
  api:
    container_name: api
    command: docker/wait-for-it.sh db:3306 -- docker/entrypoint.sh
    build: .
    restart: always
    volumes: 
      - .:/api
    ports:
      - "9000:9000"
    networks: 
      - app-network
    depends_on: 
      - db
    links:
      - db
    environment:
      - NODE_ENV=production
  db:
    build: docker/mysql
    container_name: db
    restart: always
    tty: true
    ports: 
      - "3306:3306"
    volumes: 
      - ./docker/mysql/dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      - MYSQL_DATABASE=api_food
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks:
      - app-network
networks: 
  app-network:
    driver: bridge